import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { FaqProvider } from "@/context/faqContext";
import { TestimoniProvider } from "@/context/testimoniContext";
import AppProvider from "@/provider/AppProvider";

const manrope = localFont({
  src: "./fonts/manrope/Manrope-Regular.ttf",
  variable: "--font-manrope",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "GenBI Jember",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${manrope.variable} antialiased`}
      >
        <AppProvider>
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
